---
deployment:
  tasks:
    - source /home/qg4j6rda9kl2/virtualenv/rbscience/3.7/bin/activate && cd /home/qg4j6rda9kl2/rbscience
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt