# Generated by Django 3.2.8 on 2021-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
