# Generated by Django 3.2.8 on 2021-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='google',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='twiter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
