# Generated by Django 3.2.8 on 2021-11-11 08:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='submenuscripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('filepdf', models.FileField(upload_to='submenupdf')),
                ('remark', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='vol',
            fields=[
                ('vol', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearbyvol', to='artical.vol')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articalbyyear', to='artical.year')),
            ],
        ),
        migrations.CreateModel(
            name='artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherauthors', models.CharField(blank=True, max_length=1000)),
                ('pdf', models.FileField(upload_to='achivesPdf')),
                ('heading', models.CharField(max_length=500)),
                ('abstract', ckeditor_uploader.fields.RichTextUploadingField()),
                ('keywords', ckeditor_uploader.fields.RichTextUploadingField()),
                ('do', models.CharField(blank=True, max_length=1000)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('authors', models.ManyToManyField(to='artical.authors')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearbyissue', to='artical.issue')),
            ],
        ),
    ]
