# Generated by Django 3.2.8 on 2021-11-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='do',
            new_name='doi',
        ),
    ]
