# Generated by Django 3.2.8 on 2021-12-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcount', models.BigIntegerField(default=0)),
                ('articalid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artical.artical')),
            ],
        ),
    ]
