# Generated by Django 3.2.8 on 2021-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_rename_do_artical_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='boardimg',
            field=models.ImageField(default='default.jpg', upload_to='articalimg'),
        ),
    ]
