# Generated by Django 3.2.6 on 2021-11-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0003_artical_boardimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('articalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.artical')),
            ],
            options={
                'unique_together': {('articalid', 'ip')},
            },
        ),
    ]
