# Generated by Django 3.2.8 on 2021-11-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0005_downloadcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcount',
            old_name='count',
            new_name='dcount',
        ),
    ]
