# Generated by Django 3.2.8 on 2021-12-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0006_rename_count_downloadcount_dcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcount',
            name='articalid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artical.artical'),
        ),
    ]
