# Generated by Django 3.2.8 on 2021-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0007_alter_downloadcount_articalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
