# Generated by Django 3.2.8 on 2021-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0008_alter_downloadcount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
