# Generated by Django 3.2.8 on 2021-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0009_alter_downloadcount_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='downloadcount',
        ),
    ]
