# Generated by Django 3.2.8 on 2021-10-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
