# Generated by Django 3.2.8 on 2021-10-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.services'),
        ),
    ]
