# Generated by Django 3.2.8 on 2021-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_faq_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img1',
            field=models.ImageField(default='', upload_to='services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='img2',
            field=models.ImageField(blank=True, upload_to='services'),
        ),
    ]
