# Generated by Django 3.2.8 on 2021-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='type',
            field=models.CharField(choices=[('service', 'service'), ('training', 'training')], default='service', max_length=10),
            preserve_default=False,
        ),
    ]
