# Generated by Django 3.2.8 on 2021-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211026_1624'),
        ('services', '0006_services_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='associatedfaculty',
            field=models.ManyToManyField(blank=True, to='team.TeamModel'),
        ),
    ]
