# Generated by Django 3.2.8 on 2021-11-11 07:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_services_associatedfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='ourresearch',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
