# Generated by Django 3.2.8 on 2021-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortdes', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='blogs/img')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
