# Generated by Django 3.2.8 on 2021-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='shortdes',
            new_name='blog_des',
        ),
        migrations.AddField(
            model_name='blogs',
            name='heading1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogs',
            name='heading1details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
