# Generated by Django 3.2.8 on 2021-10-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20211022_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='detail',
            new_name='blog_detail',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='heading1details',
        ),
    ]
