# Generated by Django 3.2.8 on 2021-10-22 09:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20211022_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
