# Generated by Django 3.2.8 on 2021-10-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_artical_authors_issue_vol_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='img',
            field=models.ImageField(blank=True, upload_to='authors'),
        ),
    ]
