# Generated by Django 3.2.8 on 2021-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_authors_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='pdf',
            field=models.FileField(default='', upload_to='achivesPdf'),
            preserve_default=False,
        ),
    ]
