# Generated by Django 3.2.8 on 2021-10-24 04:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_artical_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='content',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='artical',
            name='do',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artical',
            name='keywords',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artical',
            name='references',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
