# Generated by Django 3.2.8 on 2021-10-24 06:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20211023_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='wp_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.BigIntegerField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_date_gmt', models.DateTimeField(auto_now=True)),
                ('post_content', ckeditor.fields.RichTextField()),
                ('post_title', models.CharField(max_length=500)),
                ('post_excerpt', models.CharField(max_length=500)),
                ('post_status', models.CharField(max_length=30)),
                ('comment_status', models.CharField(max_length=20)),
                ('ping_status', models.CharField(max_length=20)),
                ('post_password', models.TextField()),
                ('pinged', models.TextField()),
                ('post_modified', models.DateTimeField()),
                ('post_modified_gmt', models.DateTimeField()),
                ('post_content_filtered', models.TextField()),
                ('post_parent', models.BigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(max_length=100)),
                ('menu_order', models.CharField(max_length=200)),
                ('comment_count', models.BigIntegerField()),
            ],
        ),
    ]
