# Generated by Django 3.2.8 on 2021-10-24 21:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_artical_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
