# Generated by Django 3.2 on 2021-10-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_artical_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='vol',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='year',
        ),
        migrations.AddField(
            model_name='issue',
            name='vol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yearbyvol', to='article.vol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articalbyyear', to='article.year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artical',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearbyissue', to='article.issue'),
        ),
    ]
