# Generated by Django 3.2 on 2021-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_artical_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.IntegerField(),
        ),
    ]
