# Generated by Django 3.2 on 2021-10-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20211024_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearbyissue', to='article.issue'),
        ),
    ]
