# Generated by Django 3.2 on 2021-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_artical_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
