# Generated by Django 3.2.8 on 2021-10-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_artical_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
