# Generated by Django 3.2.8 on 2021-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_artical_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='otherauthors',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
