# Generated by Django 3.2.8 on 2021-11-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_artical_otherauthors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artical',
        ),
    ]
