# Generated by Django 3.2.8 on 2021-11-10 10:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_delete_artical'),
    ]

    operations = [
        migrations.CreateModel(
            name='artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherauthors', models.CharField(blank=True, max_length=1000)),
                ('pdf', models.FileField(upload_to='achivesPdf')),
                ('heading', models.CharField(max_length=500)),
                ('abstract', ckeditor.fields.RichTextField()),
                ('keywords', ckeditor.fields.RichTextField()),
                ('do', models.CharField(blank=True, max_length=1000)),
                ('references', ckeditor.fields.RichTextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('authors', models.ManyToManyField(to='article.authors')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearbyissue', to='article.issue')),
            ],
        ),
    ]
