# Generated by Django 3.2.8 on 2021-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='type',
            field=models.CharField(choices=[('1', 'mainsite'), ('2', 'Journal Publication')], default='1', max_length=1),
        ),
    ]
