# Generated by Django 3.2.8 on 2021-10-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_blogs_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
