# Generated by Django 3.2.8 on 2021-10-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_servicescontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescontact',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
