# Generated by Django 3.2.8 on 2021-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_servicescontact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicescontact',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
