# Generated by Django 3.2.8 on 2021-11-11 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstuctionsToAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
