# Generated by Django 3.2.8 on 2021-11-11 07:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_instuctionstoauthors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instuctionstoauthors',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
