# Generated by Django 3.2.8 on 2021-11-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_instuctionstoauthors_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditorialboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Chief Editor'), (2, 'Editors')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('positon', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
