# Generated by Django 3.2.8 on 2021-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auditorialboardmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorialboardmodel',
            old_name='positon',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='auditorialboardmodel',
            name='type',
            field=models.CharField(choices=[('1', 'Chief Editor'), ('2', 'Editors')], max_length=20),
        ),
    ]
