# Generated by Django 3.2.8 on 2021-11-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20211111_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auditorialboardModel',
            new_name='auditorialBoard',
        ),
    ]
