# Generated by Django 3.2.8 on 2021-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
                ('tsl', models.BooleanField()),
                ('ssl', models.BooleanField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
