# Generated by Django 3.2.8 on 2021-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_emailsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsetup',
            name='activate',
            field=models.BooleanField(default=False, help_text='other mail is automatically disabled'),
            preserve_default=False,
        ),
    ]
