# Generated by Django 3.2.8 on 2021-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_emailsetup_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetup',
            name='port',
            field=models.IntegerField(max_length=10),
        ),
    ]
