# Generated by Django 3.2.8 on 2021-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_alter_emailsetup_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='nortificationMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
