# Generated by Django 3.2.8 on 2021-11-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_aboutcontace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutContace',
            new_name='aboutContact',
        ),
    ]
