# Generated by Django 3.2.8 on 2021-11-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_rename_aboutcontace_aboutcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutContact',
        ),
    ]
