# Generated by Django 3.2.8 on 2021-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_delete_aboutcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetup',
            name='port',
            field=models.IntegerField(),
        ),
    ]
