# Generated by Django 3.2.8 on 2021-12-22 08:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_alter_emailsetup_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='openAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
