# Generated by Django 3.2.8 on 2021-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmodel',
            name='img',
            field=models.ImageField(default='', upload_to='research'),
            preserve_default=False,
        ),
    ]
