# Generated by Django 3.2.8 on 2021-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
