# Generated by Django 3.2.8 on 2021-10-27 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmodel',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchmodel',
            name='overview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
