# Generated by Django 3.2.8 on 2021-10-27 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_researchmodel_projectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='projectDetails',
            field=ckeditor.fields.RichTextField(default='<p><strong>RESEARCH NAME</strong> : Nuclear Micro-Reactors</p><p><strong>CLIENT </strong>: Envato Pvt Ltd</p><p><strong>CATEGORY :</strong>&nbsp;Biosafety, Incubator</p><p><strong>DELIVERY MODE :</strong>&nbsp;Stipulated Price</p><p><strong>LOCATION :</strong>&nbsp;USA</p>'),
        ),
    ]
