# Generated by Django 3.2.8 on 2021-10-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20211027_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
                ('researchModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='research.researchmodel')),
            ],
        ),
    ]
