# Generated by Django 3.2.8 on 2021-11-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchModel', to='research.category'),
        ),
    ]
