# Generated by Django 3.2.8 on 2021-11-11 07:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_researchmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='researchmodel',
            name='processOverview',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='researchmodel',
            name='projectDetails',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p><strong>RESEARCH NAME</strong> : enter here..</p><p><strong>CLIENT </strong>: enter here..</p><p><strong>CATEGORY :</strong>enter here..</p><p><strong>DELIVERY MODE :</strong>enter here..</p><p><strong>LOCATION :</strong>enter here..</p>'),
        ),
    ]
